@startuml demo_standard

state Top {

    state "**State_A**" as State_A : //entry:// entry action 1\n\t   entry action 2\n//do://  do action 1\n\tdo action 2\n//exit://   exit action 1\n\t   exit action 2
    state "**State_B**" as State_B : //entry:// entry action 1\n\t   entry action 2\n//do://  do action 1\n\tdo action 2\n//exit://   exit action 1\n\t   exit action 2
    state "**State_C**" as State_C : //entry:// entry action 1\n\t   entry action 2\n//do://  do action 1\n\tdo action 2\n//exit://   exit action 1\n\t   exit action 2
    state "**State_D**" as State_D : //entry:// entry action 1\n\t   entry action 2\n//do://  do action 1\n\tdo action 2\n//exit://   exit action 1\n\t   exit action 2
    state "**State_E**" as State_E : //entry:// entry action 1\n\t   entry action 2\n//do://  do action 1\n\tdo action 2\n//exit://   exit action 1\n\t   exit action 2
    state "**State_F**" as State_F : //entry:// entry action 1\n\t   entry action 2\n//do://  do action 1\n\tdo action 2\n//exit://   exit action 1\n\t   exit action 2
    state "**State_G**" as State_G : //entry:// entry action 1\n\t   entry action 2\n//do://  do action 1\n\tdo action 2\n//exit://   exit action 1\n\t   exit action 2

    state c1 <<choice>>
    state c2 <<choice>>
    state c3 <<choice>>
    state c4 <<choice>>

    c1 --> State_C : [true]
    c1 --> State_D : [false]
    c2 --> State_A : [true]
    c2 --> State_G : [false]
    c3 --> c4 : [true]
    c3 --> State_D : [false]
    c4 --> State_C : [true]
    c4 --> State_G : [false]
    State_A --> c2 : **a long event name** /\l  [a subsequent condition]
    State_A --> State_G : **a long event name**
    State_B --> State_F : **a long event name**
    State_C --> c1 : **a long event name** /\l  [a subsequent condition]
    State_C --> State_G : **a long event name**
    State_D --> State_E : **a long event name**
    State_E --> State_D : **a long event name**
    State_E --> State_G : **a long event name**
    State_F --> c3 : **a long event name** /\l  [a subsequent condition]
    State_F --> State_C : **a long event name**
    State_F --> State_G : **a long event name**
    State_G --> Top : **a long event name**
    Top --> State_A : **a long event name**
    Top --> State_G : **a long event name**
    Top --> State_G : **a long event name**
}

@enduml
