@startuml demo_improved

!include https://raw.githubusercontent.com/davmf/plantuml-utilities/develop/state_machine_routines.iuml

$super_state("Top") {
    $entry_point("Top_entry")
    $state("State_A", $tags="s0")
    $state("State_B")
    $state("State_C", $tags="s2")
    $state("State_D", $tags="s2 s3")
    $state("State_E", $tags="s2 s3")
    $state("State_F")
    $state("State_G")

    $transition("[*]", "", "State_B", $tags="")
    $transition("State_F", $event("long transition label"), "State_C", $tags="s2")
    $transition("State_F", $event("medium transition label"), "State_G", $tags="s1")
    $transition("State_G", $event("long transition label"), "Top_entry", $tags="")
    $transition("State_D", $event("long transition label"), "State_E", $tags="s2 s3")
    $transition("State_E", $event("long transition label"), "State_D", $tags="s3")
    $transition("State_E", $event("medium transition label"), "State_G", $tags="s2 s3")
    $transition("State_C", $event("short transition label"), "State_G", $tags="s0")
    $transition("State_B", $event("long transition label"), "State_F", $tags="")
    $transition("Top_entry", $event("long transition label"), "State_G", $tags="s0")
    $transition("Top_entry", $event("short transition label"), "State_A", $tags="s0")
    $transition("Top_entry", $event("medium transition label"), "State_G", $tags="s0")
    $transition("State_A", $event("medium transition label"), "State_G", $tags="s0")
    $transitions_1_choice("State_C", $event("short transition label"), "State_C", "State_D", $t2="short transition label", $t3="short transition label", $tags1="s2", $tags2="s0", $tags3="s2")
    $transitions_1_choice("State_A", $event("long transition label"), "State_A", "State_G", $t2="short transition label", $t3="short transition label", $tags1="s0", $tags2="s0", $tags3="s0")
    $transitions_2_choices("State_F", $event("long transition label"), "State_D", "State_C", "State_G", $t2="short transition label", $t3="short transition label", $t4="short transition label", $t5="short transition label", $tags1="s3", $tags2="s3", $tags3="s0", $tags4="s0", $tags5="s0")
}

@enduml
